// AUTOGENERATED FILE!!! DO NOT EDIT
// Generated by NetworkSortGen.java on 2024-07-02

struct Pair {
    vec4 color;
    float depth;
};

void swap(int i, int j, inout Pair arr[6]) {
    Pair temp = arr[i];
    arr[i] = arr[j];
    arr[j] = temp;
}

void compareAndSwap(int i, int j, inout Pair arr[6]) {
    if(arr[i].depth < arr[j].depth) {
        swap(i, j, arr);
    }
}

void networkSort1(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort2(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort3(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort4(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort5(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort6(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort7(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort8(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort9(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort10(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort11(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort12(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort13(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort14(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort15(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort16(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort17(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort18(inout Pair arr[6]) {
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort19(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort20(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort21(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort22(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort23(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort24(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort25(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort26(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort27(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort28(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort29(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort30(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort31(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort32(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort33(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort34(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort35(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort36(inout Pair arr[6]) {
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort37(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort38(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort39(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort40(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort41(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort42(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort43(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort44(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort45(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort46(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort47(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort48(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort49(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort50(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort51(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort52(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort53(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort54(inout Pair arr[6]) {
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort55(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort56(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort57(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort58(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort59(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort60(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort61(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort62(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort63(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort64(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort65(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort66(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort67(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort68(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort69(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort70(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort71(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort72(inout Pair arr[6]) {
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort73(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort74(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort75(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort76(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort77(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort78(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort79(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort80(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort81(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort82(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort83(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort84(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort85(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort86(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort87(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort88(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 3, arr);
  compareAndSwap(2, 6, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort89(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 4, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 5, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

void networkSort90(inout Pair arr[6]) {
  compareAndSwap(1, 6, arr);
  compareAndSwap(2, 5, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(1, 5, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 6, arr);
  compareAndSwap(1, 2, arr);
  compareAndSwap(3, 4, arr);
  compareAndSwap(5, 6, arr);
  compareAndSwap(2, 3, arr);
  compareAndSwap(4, 5, arr);
  compareAndSwap(3, 4, arr);
}

